# Generated by Django 2.2 on 2019-05-02 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id_farmer', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Parceagri',
            fields=[
                ('id_parcelle', models.AutoField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id_polygon', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROIPolygone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('lat', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Lontitude')),
                ('id_polygon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_pol', to='servAgri.Polygon')),
            ],
        ),
        migrations.CreateModel(
            name='Donnecap',
            fields=[
                ('id_donnecap', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('data_type', models.CharField(default=0, max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('psg_lat', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('psg_lon', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('pid_lat', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('pid_lon', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('image_spectrum', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('id_farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_f', to='servAgri.Farmer')),
                ('id_parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_parc', to='servAgri.Parceagri')),
            ],
        ),
    ]
