# Generated by Django 2.2 on 2019-05-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servAgri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceagri',
            old_name='id_farm',
            new_name='id_farmer',
        ),
        migrations.RemoveField(
            model_name='parceagri',
            name='pointDescription',
        ),
    ]
